name: ETH Weekly Put Bot (Daily 06:00 TH)

on:
  schedule:
    - cron: "0 23 * * *"   # 06:00 TH = 23:00 UTC ของวันก่อนหน้า
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check env
        run: |
          test -n "$OPENAI_API_KEY" || (echo "OPENAI_API_KEY missing" && exit 1)
          test -n "$BOT_TOKEN" || (echo "BOT_TOKEN missing" && exit 1)
          test -n "$CHAT_ID" || (echo "CHAT_ID missing" && exit 1)
          echo "All env present."
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python weekly_put_reco.py
